FROM docker.io/nvidia/cuda:{{ cuda_version }}-cudnn-runtime-ubuntu{{ ubuntu }}

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

LABEL org.opencontainers.image.description Docker image with python {{ python_version }}.

# System deps
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        vim-gtk3 \
        git \
        build-essential \
        curl \
        wget \
        cmake \
        xclip {% if include_latex %}\
        # texlive-full \
        texlive-latex-base \
        texlive-latex-recommended \
        texlive-latex-extra \
        texlive-bibtex-extra \
        texlive-fonts-recommended \
        texlive-fonts-extra \
        dvipng \
        cm-super
    {% endif %}

# ----------------------------
# Install micromamba
# ----------------------------
ENV MAMBA_ROOT_PREFIX=/opt/micromamba
ENV PATH=$MAMBA_ROOT_PREFIX/bin:$PATH

RUN curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj -C /usr/local/bin --strip-components=1 bin/micromamba

# ----------------------------
# Create Python environment
# ----------------------------
RUN micromamba create -y -n pyenv -c conda-forge python={{ python_version }} && \
    micromamba clean --all --yes

ENV PATH=$MAMBA_ROOT_PREFIX/envs/pyenv/bin:$PATH
ENV CONDA_DEFAULT_ENV=pyenv

RUN rm -rf /var/lib/apt/lists/*

ARG UID=1000
ARG GID=1000
ARG USERNAME=non_root

# Create user
{% if not use_root %}
# Create user
RUN set -eux; \
    # If UID exists → rename that user
    if id -u $UID >/dev/null 2>&1; then \
        EXISTING_USER=$(id -nu $UID); \
        usermod -l $USERNAME $EXISTING_USER; \
        usermod -d /home/$USERNAME -m $USERNAME; \
    else \
        useradd -m -u $UID -g $GID -s /bin/bash $USERNAME; \
    fi; \
    # Ensure group exists
    if ! getent group $GID >/dev/null; then \
        groupadd -g $GID $USERNAME; \
    fi

ENV HOME=/home/$USERNAME
USER $USERNAME
{% else %}
ENV HOME=/root
{% endif %}

USER root

# Python deps
RUN pip install --no-cache-dir --upgrade pip setuptools wheel \
    ipython matplotlib numpy scipy pandas pre-commit && \
    pip install --no-cache-dir \
    torch torchvision torchaudio

# ----------------------------
# Git config
# ----------------------------
RUN git config --global --add safe.directory /workspace && \
    git config --global core.editor "vim" && \
    git config --global alias.lga "log --all --graph --decorate --oneline" && \
    git config --global alias.lg "log --graph --decorate --oneline" && \
    git config --global alias.lgac "log --all --graph --decorate --pretty=format:'%C(yellow)%h%Creset %C(green)%cn%Creset %C(auto)%d%Creset %C(white)%s%Creset'" && \
    git config --global alias.lgc "log --graph --decorate --pretty=format:'%C(yellow)%h%Creset %C(green)%cn%Creset %C(auto)%d%Creset %C(white)%s%Creset'"
    
# ----------------------------
# Vim setup
# ----------------------------
USER $USERNAME

# Install vim-plug
RUN curl -fLo ${HOME}/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        
# Copy your vimrc template
{% if use_root %}
COPY templates/.vimrc_template ${HOME}/.vimrc
{% else %}
COPY templates/.vimrc_template ${HOME}/.vimrc
{% endif %}

# Install plugins (headless)
RUN vim +PlugInstall +qall

# Set workdir
WORKDIR /workspace

# Set initial command
ENTRYPOINT ["/bin/bash"]
