FROM python:{{ python_version }}-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

LABEL org.opencontainers.image.description Docker image with python {{ python_version }}.

# System deps
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        vim-gtk3 \
        git \
        build-essential \
        curl \
        wget \
        cmake \
        xclip \
        python3-tk {% if include_latex %}\
        texlive-full \
        texlive-latex-base \
        texlive-latex-recommended \
        texlive-latex-extra \
        texlive-bibtex-extra \
        texlive-fonts-recommended \
        texlive-fonts-extra \
        dvipng \
        cm-super
    {% endif %}
RUN rm -rf /var/lib/apt/lists/*

# Create user
{% if not use_root %}
# Create user
RUN useradd -m non_root
ENV HOME=/home/non_root
{% else %}
ENV HOME=/root
{% endif %}

# Using root for installation
USER root

# Python deps
RUN pip install --no-cache-dir --upgrade pip setuptools wheel \
    ipython matplotlib numpy scipy pandas pre-commit && \
    pip install --no-cache-dir \
    torch torchvision torchaudio \
    --index-url {{ pytorch_cpu_index }}

# ----------------------------
# Git config
# ----------------------------
RUN git config --global --add safe.directory /workspace && \
    git config --global core.editor "vim" && \
    git config --global alias.lga "log --all --graph --decorate --oneline" && \
    git config --global alias.lg "log --graph --decorate --oneline" && \
    git config --global alias.lgac "log --all --graph --decorate --pretty=format:'%C(yellow)%h%Creset %C(green)%cn%Creset %C(auto)%d%Creset %C(white)%s%Creset'" && \
    git config --global alias.lgc "log --graph --decorate --pretty=format:'%C(yellow)%h%Creset %C(green)%cn%Creset %C(auto)%d%Creset %C(white)%s%Creset'"
    
# ----------------------------
# Vim setup
# ----------------------------
{% if not use_root %}
USER non_root
{% endif %}

# Install vim-plug
RUN curl -fLo ${HOME}/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        
# Copy your vimrc template
{% if use_root %}
COPY templates/.vimrc_template ${HOME}/.vimrc
{% else %}
COPY --chown=non_root:non_root templates/.vimrc_template ${HOME}/.vimrc
{% endif %}

# Install plugins (headless)
RUN vim +PlugInstall +qall

# Set workdir
WORKDIR /workspace

# Set initial command
ENTRYPOINT ["/bin/bash"]
